"""Language-code helpers for Wiktionary etymology templates.

Wiktionary language codes are broad and occasionally edition-specific. This table
covers common source languages in English etymologies and keeps unknown codes as
readable code labels so extraction remains loss-tolerant.
"""

LANGUAGE_CODE_TO_NAME = {
    "aa": "Afar",
    "ab": "Abkhaz",
    "ae": "Avestan",
    "af": "Afrikaans",
    "akk": "Akkadian",
    "ang": "Old English",
    "ar": "Arabic",
    "arc": "Aramaic",
    "az": "Azerbaijani",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "bo": "Tibetan",
    "br": "Breton",
    "ca": "Catalan",
    "cel-pro": "Proto-Celtic",
    "cop": "Coptic",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "dum": "Middle Dutch",
    "el": "Greek",
    "enm": "Middle English",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "fa": "Persian",
    "fi": "Finnish",
    "fro": "Old French",
    "fr": "French",
    "frk": "Frankish",
    "frm": "Middle French",
    "ga": "Irish",
    "gd": "Scottish Gaelic",
    "gem-pro": "Proto-Germanic",
    "gmh": "Middle High German",
    "gmw-pro": "Proto-West Germanic",
    "got": "Gothic",
    "grc": "Ancient Greek",
    "grc-koi": "Koine Greek",
    "he": "Hebrew",
    "hi": "Hindi",
    "hit": "Hittite",
    "hu": "Hungarian",
    "hy": "Armenian",
    "id": "Indonesian",
    "ine-pro": "Proto-Indo-European",
    "ira-pro": "Proto-Iranian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "ka": "Georgian",
    "ko": "Korean",
    "la": "Latin",
    "la-cla": "Classical Latin",
    "la-lat": "Late Latin",
    "la-med": "Medieval Latin",
    "la-new": "New Latin",
    "la-vul": "Vulgar Latin",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mg": "Malagasy",
    "mi": "Maori",
    "mkh-pro": "Proto-Mon-Khmer",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "ms": "Malay",
    "mul": "Translingual",
    "nan": "Min Nan",
    "nl": "Dutch",
    "non": "Old Norse",
    "no": "Norwegian",
    "xno": "Anglo-Norman",
    "oc": "Occitan",
    "ota": "Ottoman Turkish",
    "peo": "Old Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sa": "Sanskrit",
    "sga": "Old Irish",
    "sla-pro": "Proto-Slavic",
    "sq": "Albanian",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "vi": "Vietnamese",
    "yi": "Yiddish",
    "zh": "Chinese",
    "cmn": "Mandarin Chinese",
    "cmn-pinyin": "Mandarin Chinese (Pinyin)",
    "cmn-wadegiles": "Mandarin Chinese (Wade-Giles)",
    "yue": "Cantonese",
    "nan-hbl": "Hokkien",
    "fa-cls": "Classical Persian",
    "sco": "Scots",
    "mni": "Meitei",
    "sh": "Serbo-Croatian",
    "sk": "Slovak",
    "gem": "Germanic languages",
    "haw": "Hawaiian",
    "goh": "Old High German",
    "nrf": "Norman",
    "inc-hnd": "Hindi-Urdu",
    "egy": "Egyptian",
    "hbo": "Biblical Hebrew",
    "gkm": "Byzantine Greek",
    "gmq": "North Germanic languages",
    "pa": "Punjabi",
    "cel-gau": "Gaulish",
    "ug": "Uyghur",
    "la-ecc": "Ecclesiastical Latin",
    "sla": "Slavic languages",
    "nci": "Classical Nahuatl",
    "mul-tax": "Taxonomic name",
    "fro-nor": "Old Northern French",
    "kw": "Cornish",
    "pal": "Middle Persian",
    "km": "Khmer",
    "te": "Telugu",
    "cel-bry-pro": "Proto-Brythonic",
    "odt": "Old Dutch",
    "dz": "Dzongkha",
    "hop": "Hopi",
    "yo": "Yoruba",
    "scn": "Sicilian",
    "gu": "Gujarati",
    "ltc": "Middle Chinese",
    "ceb": "Cebuano",
    "ne": "Nepali",
    "osx": "Old Saxon",
    "gsw": "Alemannic German",
    "am": "Amharic",
    "zh-postal": "Postal Romanization",
    "cmn-tongyong": "Tongyong Pinyin",
    "qu": "Quechua",
    "tpw": "Old Tupi",
    "oj": "Ojibwe",
    "fa-ira": "Iranian Persian",
    "si": "Sinhalese",
    "qsb-grc": "Pre-Greek",
    "xcb": "Cumbric",
    "trk": "Turkic languages",
    "sux": "Sumerian",
    "nan-tws": "Teochew",
    "tnq": "Taino",
    "xpi": "Picard",
    "mk": "Macedonian",
    "nah": "Nahuatl languages",
    "kk": "Kazakh",
    "es-MX": "Mexican Spanish",
    "cel-bry": "Brythonic languages",
    "mga": "Middle Irish",
    "alg": "Algonquian languages",
    "kn": "Kannada",
    "ett": "Etruscan",
    "zu": "Zulu",
    "phn": "Phoenician",
    "rom": "Romani",
    "jam": "Jamaican Patois",
    "enm-nor": "Northern Middle English",
    "ig": "Igbo",
    "jv": "Javanese",
    "iu": "Inuktitut",
    "fy": "West Frisian",
    "trk-pro": "Proto-Turkic",
    "azc-nah": "Nahuan languages",
    "osp": "Old Spanish",
    "cr": "Cree",
    "roa-oit": "Old Italian",
    "dsb": "Lower Sorbian",
    "ha": "Hausa",
    "yxg": "Yagara",
    "gmw-msc": "Middle Scots",
    "sem": "Semitic languages",
    "vec": "Venetian",
    "ibl": "Ibaloi",
    "so": "Somali",
    "as": "Assamese",
    "xdk": "Dharug",
    "syc": "Classical Syriac",
}


def language_name(code: str | None) -> str | None:
    if not code:
        return None
    code = code.strip()
    if not code or code == "-":
        return None
    return LANGUAGE_CODE_TO_NAME.get(code, code)
